// Purpose: Generate possibleTypes.json to pass as parameter when initializing
// InMemoryCache in frameworks/gql/index. Enables usage of fragments with
// unions and interfaces in GraphQL queries.

// Source Documentation: https://www.apollographql.com/docs/react/data/fragments/#using-fragments-with-unions-and-interfaces

import { getConfig } from '@src/config';
import * as fs from 'fs';
import * as path from 'path';

const fetch = require('cross-fetch');

const { GOERLI_GRAPH_API_URL } = getConfig();

const homeDirectory = path.resolve(process.cwd());
const destinationDirectoryJS = '/src/core/frameworks/gql/possibleTypes.js';
const destinationPathJS = path.join(homeDirectory, destinationDirectoryJS);

console.log('home directory: ', homeDirectory);
console.log('destination path: ', destinationPathJS);

fetch(`${GOERLI_GRAPH_API_URL}`, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    variables: {},
    query: `
      {
        __schema {
          types {
            kind
            name
            possibleTypes {
              name
            }
          }
        }
      }
    `,
  }),
})
  .then((result: Response) => result.json())
  .then((result: any) => {
    const possibleTypes: { [key: string]: string[] } = {};

    result.data.__schema.types.forEach((supertype: any) => {
      if (supertype.possibleTypes) {
        possibleTypes[supertype.name] = supertype.possibleTypes.map((subtype: any) => subtype.name);
      }
    });

    fs.writeFile(
      destinationPathJS,
      `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n/* eslint-disable prettier/prettier */\nexport const possibleTypes = ${JSON.stringify(
        possibleTypes
      )};`,
      (err) => {
        if (err) {
          console.error('Error writing possibleTypes.ts', err);
        } else {
          console.log('Fragment types successfully extracted!');
        }
      }
    );
  });
